spring:
  application.name: scheduler
  datasource:
    name: dataSource
    username: sa
    password: password
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
flyway:
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  enabled: true
  locations: classpath:db/migration

scheduler.quartz-properties:
  org.quartz.jobStore:
    misfireThreshold: 60000
    class: org.quartz.impl.jdbcjobstore.JobStoreTX
    driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    useProperties: true
    tablePrefix: QRTZ_
    isClustered: true
    clusterCheckinInterval: 20000
  org.quartz.scheduler:
    instanceName: scheduler-name
    instanceId: AUTO
    skipUpdateCheck: true
  org.quartz.threadPool:
    class: org.quartz.simpl.SimpleThreadPool
    threadCount: 20
    threadPriority: 4

helloWordJob.cron:  1/4 * * * * ?